FAILED! => {"changed": true, "cmd": "for mode in seqwr seqrd randwr randrd; do\n  sysbench fileio --file-total-size=1G --file-test-mode=$mode run >> /tmp/disk_results_$mode.txt\ndone\n", "delta": "0:00:10.193951", "end": "2025-02-20 20:29:16.686188", "msg": "non-zero return code", "rc": 1, "start": "2025-02-20 20:29:06.492237", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

Traceback (most recent call last):
  File "/root/genral-python-scripts/sysbench/./sysbench.py", line 87, in <module>
    main()
  File "/root/genral-python-scripts/sysbench/./sysbench.py", line 82, in main
    run_ansible_playbook()
  File "/root/genral-python-scripts/sysbench/./sysbench.py", line 63, in run_ansible_playbook
    subprocess.run(["ansible-playbook", "-i", "inventory", "sysbench_playbook.yml"], check=True)
  File "/usr/local/python312/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ansible-playbook', '-i', 'inventory', 'sysbench_playbook.yml']' returned non-zero exit status 2.
atal: [hqxsb19-7cs2o282]: FAILED! => {"changed": false, "cmd": "mkdir -p /tmp/sysbench_test_files\nsysbench fileio --file-total-size=1G --file-num=64 prepare\n", "delta": null, "end": null, "msg": "Unable to change directory before execution: [Errno 2] No such file or directory: '/tmp/sysbench_test_files'", "rc": null, "start": null, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
